apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1yxI92TLeMg3hj4G45vL30pEyI6L15F/EmnOdDr8i4ZGRplOu8Jy3rrGShWgqUEmBeZYb3eMkEGSVhqrO19U52RE8306OCDbhxcyPywpCiEnHBrsUScJsYZB7VEN5rl/gRRjHTwZHnIGL1Wbqo+VBAZQ0hBrpxApuxhMbjM7QbuoQdQ30E6url9kcob/dcj5BhG6B3V5aJRe3ehptkjAiiEXrOqNguI1CsgRpO2szErj9iGEoZByXESSyYqqkGGiLVJ8hAVCMQBb3L1TAYjqb2PFdTZ3UQFZkmsoCWV1R0x+haFr2Jj/2V/3gZRpBbyuB3RFLovUKL7tN19hA851dymvt7sqUtqSfnDEjATdaYE47xCPBe4YHoj/v7dzbaCb,iv:7ZTDLHQ6xxaLWjCyBhb7fPYcPDykW3Xxu85+Q17optU=,tag:aCFA1LtgRb8bPBVa45VU+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:I6lJhC2ziOCrJPwCTMFoYVprsigVu7JovUFw0oyKB5Zei2vm0v8hJ5Hx5oLCYGV0zJmNF7kfKD90eSR9lKkiGgE3u+Qcum2KIgVC7tqkAiHuC7JrZbv+vlVbeZdeqDkYU/Wimp4DcoFh5+BO3TMyLg+hUNgbaLW3L8iZWG1DPQUqL4KQCBjJ4foWcOwsY8B0VwdJFHAheniTxfpSDEAK9PJaDLRBSuYOsDtsRnbETg9jCWQbd7UzJ3/VLw915RdukVDNGrvSvv18Rxl3Bw==,iv:UDfyhm4SC9HbVnOcD8TpnnnCtIrenb7anoOxn5cwtfM=,tag:nuYTJ2RJogVU0thp9YWUqg==,type:str]
    known_hosts: ENC[AES256_GCM,data:np4DMfwFs3WxuaGmUb1Ysml0s25COsLQXCXTaFwzHxyvvunjfkuPe5m0tX6k8FZiI3b8VOSQboB/FCNrSlEttF3EX5dDsUln86NucVcvGSghPM4utOw24Y8mHxqhVEZkaxgezxJu2BBRPAU7vSN6BGWaUvdSVFznGNxHbQ/GTUsINs9e/jfUzVXkAbcm/QT4K+GaiLhpOYurjTBm1IjWzseCBef1LKGggpFh,iv:hEYAjhO+/SWWUOY3LwoxMEt6B82sqq/yj707G94mW34=,tag:Wv6dJh60nY1ZL/GC2mQFAg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcHJFSEl0TXo4azU0QU5x
            eisrUjZmb25uWmcyTnIvditRMW5QV1NqeFFZCkVNY3NwNlJJQjJnV280V1lnc0xB
            NTEwS2J2Vk5Sd012ZUtDUWgvV0Jhc2cKLS0tIDRPd0I1R01jR2VzcE05ODJhZFk4
            RnRiOGZFaXg1Mk1hcjdDbWVoT0ZVOUUK4geq/OxhnDcWvRlkmiBgw8/4c6OQ5Z+9
            2SZc5hDPmX+HxQQBPE1zDwg+B2e7PgOKTABBoISG1ealbDna+SAAQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:18:18Z"
    mac: ENC[AES256_GCM,data:q/L2uZNyPTWhcgv2ZcsMphLGcJNlJT6tJpEsI435ZNR248tCA10j2UkJm8jBCuHiUt1uDmv5nsAT3fRn30D3EF7VgDVl3wllg8tI/N7ZVBBIII24xPlLIYaCM5CJIurYRGBAeFdn+44JGCriOdR7OE9Kt5NV/9rhtrsvWKWPfXQ=,iv:2mb79qyY3lTxQddUGXi/rdRGj6sfqhju9SjLnVZImUc=,tag:T1EYhNMB6eD+yzM4gZbg4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
