apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:J2U2raw6/L37+kn8t74KEpD8Qewdc/LXIJMr1M3vaMJB4Dlz56SvV805oBz607SL/nw0nS9B5EYUZlSYT3cyfTOp8uWrxBz1H7FoEsGW1gKpfIHFLP2uJ4qJMH2CVocuPqLtIluLXWhD10dM853tw3CYL5PRP6nJVDlWoiL8y1bN177hIkynmT4fJ1etZL0il49A+38Wu/N9mkwGnVt/Ir7P9XGbYfwFnQ/bky8CMUVe38ZqFQo2ValmEWKBlwwe1tAK2sC5n3GwtgJIJKmab4ZwFmUSgqPsO3p601B9CetzaPwIgQU5gLOZFWBAY2qAgTSA95ssVqy2HbYc+/Tz/AZWfWObRb5FcTyY3g3UwiasY4fe1ZN0yiah9+Oe1t3y,iv:2IxAYC4BNs8ItmBgAvrerSvXwmYrNmDwpoW4fhyUKNY=,tag:/uafimN2Ogc8WbtfggqOXA==,type:str]
    identity.pub: ENC[AES256_GCM,data:EdI3h3G9n+0BcnvYffywnGY9FeweVCwRqnteLBvKW4dUYA4d1jp9fEqAF8LbEsCz+CevrmoBgFU5kIwvx/Hv41JGyx0BzLxACqCPb6LMYKH10RpU0Yp/uaKWXBfRmrYmLlm+XXcrPurSJUQfMUIbdabdoTkKGoruhJLuRJxZtfVamQmkMgZbcWEW+5a1H60B4HWa/JBMqZa3XfuiFGMH5t/KG+a1+QfvzAngityhgR4zZ0fqZ06CP84zjxIu3ztTHbNe4JxpLjBouREylA==,iv:o3p91HAMgboB7TVifyHKYsBbKUpGFz7p2KkC+/d4aI8=,tag:VqalZu1Z1wNQgtUsPTTAZg==,type:str]
    known_hosts: ENC[AES256_GCM,data:5+WP5BolUnH1YEGkqK571vLSqHpNWo8LiFgpPSClPwfPV/PM8I10GBDMRWXTlBj4s003E2fO85ovukMV+vo9M9SZUaQHuvF++oBrGN+1NQ/EZkkvZ+Fcc2oBb0laKsGNG9KlxD5cVBZ7AWmTLiBRmkLiIke1mCWRK8H3tke2vRb6GfKdl84WbdYlwU8gRxBkr4RF0DZRuExOJlgwn4KbQ9ZEloXOGsg90zYH,iv:h8FMYU/eKjHxIvGGklkPV3HoVGbwVvIpu/eu5mHHH3M=,tag:io2503+q/sBX7QIbYx4ndQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUHRXWTd4bExGTlNtS3VE
            ZUw1cHowb3ptY2FRdEc2TzBTVTJsRjZBQlR3Ckxwdkp2bHRub1IxRzB4YnRPTlFM
            SnRYOE5mZlpaVldiQkxFUWJUVjBpZjQKLS0tIDU4eURnSFRYNGZUMXZ0VXo3dnc5
            TE1EY0lzNDRaOUkybXBvRS9abU1EOFUKzK9mMTow+wVDIGRT0sB2bpWoZcQ1LlRC
            PbRV8D2x7trHbPXHzG67dYeC0PjniyNQszLqt3lnFaT3HAc93/cZ2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T14:58:53Z"
    mac: ENC[AES256_GCM,data:gY2rQv0SB8n94uvbbK01qO7xoXa8Dxre4fKoCcnRfXA3x2OayqmEXMTzeQXoCRhE2dWd7VRov4It81M2Rs/3YBMCRbflL7nbbATYEIU6rauUG5suKibRmul2cD72vPW4owgGb44dbcDynFVWUFjxfVHosmGZFqHxiezAvZ7/fA4=,iv:xSaz8JaNpguf5ZaN5jA+u6LxfOsrLL/32mBNJSAekko=,tag:5NQ9NRFogBjNVXYdrXgT4Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
