apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ys34g5ikrm0cg6dGWugaw9eBOW3PY6zO45GHLPD3iacZM3aj7/DLGa1S0hfgz0WQCD7ORmlqQsZ8CrCE/73nT55TCQrp45+o4NQClRqzipogE7/RDRZ5f1SXNzg4HCbf5o3G4pfR/ubPqw/r55wx0/DKJ+OF7oH/R0OYdfWimw4SJxb+q60uT38MdIcVrreFcTnC7yqpj0VyK0YcGf33GhHteN4yVJrLPn1sjNOFjqF7C+WWQekRjWm4Ly0ZX71KsQ2ebCrtS0pX2heH7iGW0w+N+DMJaFLR1k4oMCXtiFG8yNr7avMzVQWesV17fHmCEOnnLimabiaIMas4MBaR1WNYvMVNbL7Bb/mvwb2k2zAa3VpJPF5zQs4GYVbRRO1J,iv:h8WVFL+zkQ8ZiZAhfbpePYpCRt+AQVQD2KrzSujGfc0=,tag:JkJzkA31k7zLl6vFn/sCHg==,type:str]
    identity.pub: ENC[AES256_GCM,data:bctaPxR1o2rzRyXIHONwRKmypC9uXl0DnT1AWKrDXoiuMLaadXHtrrJMWlOaG/kr5H8btnCU2MQoXZyhFAh3vhQUOgK8SQfG66zoNVYe/TDFhq/1R605i2AY28Rval4Y5LAKg27DKdPrctA2XtGeayjHA2XjMtc/xiat0dZi6KR38stzxUKQ10hAMdHjC4Lf1rQhj1YIa6dQdK9HEXT7WWNgRBR4r49Px9gZyDC4gylE+2eNGJfNWSBXzIc0sTF9kBOyRJVAVJQRoKmvxw==,iv:YO3zjvB4VoJ0Bq81C8KkQGN+1QH4mF0p4Hn9EnGmI38=,tag:SzUBoSSpnbtdM3foV9AYDQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ncrgBpDM762Ppa3enp3DszOug+tHAjYD/Mc6iiEEzD5eX8wn7TOEnhrGa76Z9VT1DasNKYqO0Zbpgpr8n1xdtnFgH/Y/Ih/Ku0d+YhfC6MemtuICKKLrq3D6wmNWmc0vpQ8Iy9n4iQZ2oxd5PhQPuUtuuF8/JO8nTDwbUVnj0SHd9M2YKGJgjiJ8Rt5N8+I0MDGdBpDOE5XEGfsGi1QvyiSte1imrSPitXZN,iv:+1+GLNkkQJtigeBfAipBmHNP6o2g3f3BZ1A35o3+62E=,tag:OgEC2Iek33/+RlHVjiWSkw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTURWNVZ6R2dBMmU0S1lM
            QVdva3ZCSEpOV1phSFQ3dDMxaXNua2JJWDE4Cno2SjZwTm1UWU01c1dLek5QRElL
            ZE9DdDJSN2tScWUrRkM2Y1pjV3Z2UzQKLS0tIE1BNVRPMUsyb2tkeDhkWTlSSFc0
            SFRvalVhK21VOW9DT3U0WlVaUVFjMXcKPw8JmLX7LA/l6EJv+pp5lRtQu+RfYQjB
            gDma5IZPAWpOGEteIEWsajNonxT5K/65ZMXHMJikxYrf0HJqGtpYXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:22:22Z"
    mac: ENC[AES256_GCM,data:RYjknJ7SD/9LHgjNcJYxyuaE6m4luvwM6aDM2QwX887GgJ619TVMYhWE03TJgLZn4cr+FO0DSZFnJDLXFmzaVLZWFSfeOWHQ7WYXothKEDR4DrobrucYJa+uNWxQSr4B+bf9txmwYkeeyhHYdqXV5uzmJtcfFpbscLwK92Ic/6g=,iv:yraPh5gqO2AUsNIRLHpzNLWJr0X1pCVFQALRCOiMfFQ=,tag:WX0hstIKvrnfX2k1hMMklQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
