apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eVRGFaUCqxrmAdZ9GYlOb5E8MYX6pvU0MaTqjo5zqE2K25odOCi5bYuUiPRkpj2A2E9iw3V37Jm43Os0wIW5hpei6lwGfeSXSgF2zfIoPPY+58EoZcAWB45gcMWrwW60I8nCL4bem4ocMoGNqVrE/aUVmr7B5J14I/UZORVg97qoZXpAiGDFOHrb175XcfdJsimaRHIWRqueh2nX4JKV9DFYRy+G/Qs5fBCD50beT9YQ883pPuTE6iyjOn0kmDmyLC5zsEPyFDgS0PjPEdkb2sQ6xJDAq1Ij4ejGSzUWr1MgbuBjqXaG+vYQzVIzSY36OLEoJldu1daoXbNL+tAiMOf+/Jid9DOK1sfDraQIfwnkzB7ozp4oMbDF92NpsW6T,iv:N3PdJR+L6EKEX4zAZ9cLQmJruRB/pj94ap8MKb+ndYs=,tag:orBgxXgp7ebayOgmKmEcZg==,type:str]
    identity.pub: ENC[AES256_GCM,data:JblojN8KiVCdoHr+Ifr21oIYlMHD7lW0xnoq8xuoa10dGIzpxDqpG7/Gx67hL15j4NIvhXCBBPzLYiGPUU83JKOWXOoDKp5XRh7yHpzltXmsPMbKyvI1/MDh06FOfAt11nf7mq4lSbP9fLBm29kWHehdJ3eL8afrUCA8gozaxwKvnQkE74jnRpx9UA/o8U/P//bKfymH2iR7kBBl1wFMw1c5YRSy9Fi1G/lKjsxQHjzfP0N5yxVi18AGsTXb7G6K5GroDVEsaqYSMqvnPw==,iv:zNJhd1P6QeV+JSU+is4gHVrKFlDQv5N2SrwJnI48mFo=,tag:8WZmc1VCoAK3SSJMKzes9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:JkvGPma2br8Oc8iBHk1SXerWZFrs4UdtBHoqrxhBNjEzdtMXRFbKtD+2wXPTSmxStIGCj/0vDCxAojvbXhqnuq11YnLuV7CoU03xMNZ7G8vIMbVmZTFMZqhIcxflfUTKGUpMQdeFiyF2QnMLGHttbEbK1Ln0WrDcsvClATG1eEKF7FfRYNE9AUK2TxJS194nmXmiS7gZ93HZSwrDjq7sh5jMR194HSYYeO2G,iv:hL0VYjLxZrD3o3xIl6FBTRyNhJcPta2ivZ4KaWbwSsw=,tag:W+u0kyIjxYSTSFtMKsGmcw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZTBlbVpxVWwvMnlXK3VR
            eldONDlSSTJXSE45L3h1cTBpTHR1alRQK3ljCkNaeStFZkp3aUx3NWR5MVlWcFph
            dndoTFRPcjFRNkh6ZXlqR3g0RzVqelkKLS0tIEYvRVRvVXFxb0hWdDZuUHNpRTRm
            QktlOXhBcnRVbWM3OEdyZGZ6MDF4VUEKDp2rBTbTvSY1GAKCyHSaantZyuxFfG2S
            uXvgc69rD/LWToluCUh3/jWh/WduAxDUufSTSTcl4kvwTZ2C7hS0yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T23:05:58Z"
    mac: ENC[AES256_GCM,data:EqzVqq6U1SJ064H8433ir0cA7Bsm6PQziKS2N8slZjbJbfDDB/BtxvzHWIp35AmrEJD6fMgcyZ9i9H9rbfQfQiy4R+C3rUuPlsE2Wsx9OGyyHBoDZH78xkjFPJm+qMN4u4FcxQ/+hWztTVhR9YStwHfA/OwP6ZM7Y5G3E3tPzas=,iv:XIjNk+RLgS9gkBm+SkJP0kUtmTu2mNZTbhUVc+u5FKQ=,tag:TNZPUKMb8Ruhnsg4syU8Nw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
