apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JLUWDJkKr2n57t/mKtaLpTInRMwLWS5ogDtPinVP2wPi8GZ27tBBQoYVRn2ELGPYjFsKdfNsum70sddVngt+QwBP1GH3TMn1b9wM7wcC7s8yBNUPV8GovtQ3sCzSv0R/V/nCQSukICwOa0vXFW9hVtbAeV89n/uCUggGaJRRCPSzGgGelYYI1aFCLWMTwxwJpxLoFot1JblBc9qPyKHK7GVGcL54Zu+iG+jO6z4wMJjXD5bjh8SEe1P5yJbHSJq1lcwkLaswZuqdlASRESUG75h047t5t7Pcn/1d/rN6Cn0LGToZ54Ify6opHjnNE2Ere9UEv88EPD56zheIlHPKeEIV1YVQB7ztpzb6T5ok0FSpOWMnIoYMMrATnc0iZN6V,iv:xVBkl7cVy0RmCVDmTBuof3RmPf9YwtroJsUk5mBClNw=,tag:ZZ8OO85Q8hcXXUO9rKj5kw==,type:str]
    identity.pub: ENC[AES256_GCM,data:CjywfflQD5vgH1mYrb4QPlcV3Fw2OlXiZv6g4Djd+EHQbCbdJDrS/Uuu1b/pz0IivlhiYUWtubVRsSwdVjIOCfhy9AzmCiK2JsoFwGG5dVrMX8/q8SJMDlzWYFIaLW4srH/nGxPYaXGtWjjC2Z5Do3NWaajnoDuuZX6itMGEkrV8G2dlDgFTWjxlUxtE9/z18sqCnnRT0JEKNbyi3bcNVaDeCeqC6YgUp70S/I6COw6rmRpgaBtLFj3ehtHjHiEUzoVdqKY5L3mhrIR/nQ==,iv:QzEP3twDJU3MVo6a22l9MdTfFSRpbTeFW3JSCilj46o=,tag:hJyLx3rBr6gcujijjOn/Lw==,type:str]
    known_hosts: ENC[AES256_GCM,data:O0RS+ljJwTyTp8uzoXct/i3epB7C8IescNhHZhHdY7Bga7mQUoRPjTtD/i0y9qu60prPc4025jJcwfBm39q3YZDFjdrx6qfPY2osYNV8zDqmufcHrvlDTNWrIApe+sjZ/3/vU0BDpD2uZrOSDhTJF70JA23O6hL3BbKVnBabVT7OMNmdTCLoqD2XdwgJezuSKM/5+1uxcR65rZp3WeA7hoE8X/+LFrsChMLI,iv:IDzc2WfhotJIGYigV8Y5RTaWKwlGjd/X7u8LMQ2w77Q=,tag:oZ6EK52XvOl1/tAIrLOBew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWlNnazN3SkM0N3BQV01E
            aVFsclNhWmhrZ09tY043YjZFUThmMzBkRWlzCmlzWWdGR2NtYlZjejlBU2ROYXVo
            cC9mR0RuenBCd1lqTlNXY3hDTG8veE0KLS0tIGxvamNXckhmRzQwYlkyNUlNWHlV
            d2Qwc3ZQeVArTkNtOTc2djdoUGRGMk0KS/Z76FSAM0xsLaJBySviLpdIdcn5Rtqv
            m0UaujMU6QCIauKEOfNt09Wh1GQR0+6FDLQmt6OpuZqsRuvMYJYngg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T16:24:32Z"
    mac: ENC[AES256_GCM,data:2JzpH4mSZwwwe459RNnpxxz2J0igob3yH6nkTVhcXrid6xGwZvGTHqgb72Ou70KQvwd8cVtF5YD3ArnAQdaX9zfPO7m48tf7vqTjz2Inh4O6I5+P8Nn6iv8SXDciN+40OnFSEiW1nvtu5udOp5aL9tj4QJIkspZM24KvcBgJJyY=,iv:Nork0KzjizSpuNHjWJ1VxqUZor2N15fGGU9VQv2V4yY=,tag:sOuc4TtdewRManQZWTPphw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
