apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:i7XDmzWC0AdVl6qIxuDbmYJnXtuIxntHTdPI9/ZbbHcPjylEvWCtP1spvxNiL7sBxugp9Xmr2euE+E4+j+ZTQ8HEhlCgEqw4Y7Uv8tsf4r0ByaXfOMJlYT1e9WKnz962MSQi2NS7tS7rAaZqaaUIBvr3YxjXAIKxjuJ8E3vwSvSylFW3lvrkPJP9DDe5xEcsmYSKGckEU4bOO82KQQQKcSHTRukX9r7mc4zDQWntXofvA0P+Uhk5Wt/HNW6mH0iBVFbXP63d+KztYFYUhZCUhZruttU3A5q3eceTvS9EXLmJZtWosoF40wc07SROoTQN6zMwmv7/UZiYvhsjRrPkoetY0DLEoag+gN9viSqtfP8A9ee1rD04TGz2PwMeZW6y,iv:GT/P4R91M4jfrMbvFpz44HWxn3SjUPTLBtwPuQlRqGE=,tag:M78aByRykWD2V7PmmiqSiQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:gTJTmi/nEVASiZrVWlikpwjaHKpa4jWpM1F2NDhF/ZKCGe0edZ8mu3R1VKsDAvd2T0JvicOmpGxlAEXfxUHTf+ECdLtJilQCtFbLsgDVG0itJeNzUIjK/kvRj+EnciPwkjKp9RLQGaywiXTB/kK7IXNqUmbz4+6eXKLrFHxxX0PzeS0vnSfx9FS/TmBEC3b/gFDhPF89w7XJuqIZtYexptkrTpbXp446j2+cH0xroedMlGwRb3rti9VQQxKQN5xbrsSJf6I0RvLhLfXFAg==,iv:pI3tqChRwdWa0swXq69ZdNNi675iMyVc2PFKn8qhCYc=,tag:rqqVRN5qcD1dI6DIc7epVg==,type:str]
    known_hosts: ENC[AES256_GCM,data:MA9z+r/YGs4yy5NV+EBEZs9jSEcn8YEsIbp13LkhhcIAoJ+IcyXT2H7O46kjsiilJB+8AooZSKhX8krrCIYG+q2QEzH6B6eLxCLStZQVHTNUU83dt1a9qf2482PsKORCOKyRc5g+0a8RUzroQt7NPg15lFywe5dQ/UBJ32qCTY6sYDpnJYpIVSMIbK573WLhuzrpXzVQi5dXEbWeLxKPi+GN52qF+jJWISPn,iv:h4alwmvcW5mepHIG/6m3S483NV/ZVkDWvBeoK2ndtZ4=,tag:Ftj8VCBrvquI0D0q91QS8w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWDUwdFpBaFllNnByQUNu
            TWwxajAwZTVVQkhCeU9NYi92a0dUOGpSWEJBCjEwbzFOdmR5RFRmUGtCdDhhSUdU
            YW8raFQwSWlGalhRVjlML0FKbVZQdGcKLS0tIEF3QkRUeFB3eXVHMUJTdHFaNnIw
            ZitXUFRVVGkrMmRSenVUZExzbUdKR2cK8P7j9K0kvAQOPPFAB5nVZGbuOPo8twnZ
            RqVJbfN8GKT7cDs6GDZn9RW3W5aGh3n5vcsHdVMP3rDsWvUEG/4oVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T20:52:04Z"
    mac: ENC[AES256_GCM,data:osoVWxEkMxRXSj8jY0T14pM8zwQp5U9vHJHPMbrVtrTVYBOvNf/v18HiQ7l6PW+jEuyabQ1X2lSipziN7zEzgluupTsmNrYa8GbSDyTKBok2xXfRmO2prKjIqEU2o9O5cnN3MDhzcinZlWSY5NuVith0J28WI+CLmsMeM7UIAMg=,iv:7zZ+ypIMfSxhhcN03Dgze6086VMb9NfdMh23M0BBIMk=,tag:6IfgpY9TvepZEV9092o0oQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
