apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:bQy3DSelw4BhI7euQNj1ptyT4E9nxWaK5fzuNGFfOf+PusO3H7syUPU7T4eXl20AGTTtXTdZ8sbKeoQz4dlWnpgRcwTLN5iT/Ys=,iv:DeqZuQ0LqSN/wvRY/aEhFZlE0sX9vYXTHI4JFLhv2LU=,tag:4lTZLXQfOwnqgnKxqN+JJQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTFlFUzd4VDhxWTFZWUQw
            UDhNcXFFMmRIMlRoTG81WVRKZ0cwWGhDdEYwCm1oSGZXU1ZBcUdWc01XWER4MExv
            MEp5YVBrVkpaT013Ri9sZU5rMS9laVEKLS0tIFFHcTFRNVFLN3M2dndFdk5pWktI
            MWpBblZEa1pwN0NhM2tiWG1JYk5vMHcKZPJ/KoOQgjjMlcGGPgwAG1sGvlHDKiKZ
            Xqy9HwtLLGVl0hwaNoIO2jk0veVAtI9DNwuebxCrNE2Jd7VAO6yERQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:22:22Z"
    mac: ENC[AES256_GCM,data:l9qqWsd1VxD8kL0Fyw4fgct4v3LO1Lm2eKPnuXpn0/ydBzyFquTV7L8YVCozjWKiC0s/owxgLNjucAWrD2pTVFi9af1nJ1YsH0jXWpBUnKYsEkT2s7OgGTCtuhaq8zuihTQbF7NY0APbVvZwfxoOJRii0TRmVhaDWze+8qZmQRs=,iv:FapNZ6FVbYDVAAF9/pYkQ6MzScRlqgcUNB00Ozw0UfA=,tag:8/i/RFMTitM+LW1AgW15Gw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
