apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:SHILZPX+oOZYu+Oe1RMAZn8hQvKBIz51hmPxw9Sjz2O+1ZywL0egKu5ellz++O/KGk9QqWCigfLUwGDas/2TEpkwC35IvHlPnck=,iv:Ad3LFvPf5glsG7kFaGRAiKwwO9OS+uZILCdUAAK6WA8=,tag:krULNFTez6yZQ/Dn9AMbZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRDhZZVNwM3VWYjJVUHh5
            eWdPclFqSzBPM1Znb2JLSjNrbEp0b0RwUGp3ClYwMFg0cFJRM3AyTmtibFVhbUFK
            eUxxUnVRNCtQalQ1SG5hSGc3dzlmb2MKLS0tICtMQlZoWC92N2cxd0lhWFU1ZEVR
            OFh1RnRsNGxLSXJDVWh2V1FpaHg5eHcKWqElrfUjyO3BZ9vVTUHWF6MA+L0SHxWe
            pxPvD6uIE/NtBmGP1R7ClBNoyKpDwCNchKU7CT3//FzOuHuKAceTWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:18:18Z"
    mac: ENC[AES256_GCM,data:lShpfpEPq9FzddtAjBg0b7F+bB/XjDMqkBK10NC4AkbNVc4iwzY1mAEkk5xVer5RmSsV7xgOsqu4Ow5o+6E6ugQiiLW27W5jVB8oc9ym40xgfriN0FbT8UDG4Z7iKZzxIyXF7YoY264MEZJSh1Ng65GvnvsipVOmPjj5Emw02hE=,iv:jDW8QB/Z9cu3LAofE1xD5zdSd9n1kXjqIo9H5a2pumM=,tag:Kz59YCYUqAQ0S5Pzx3Qvcw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
