apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:deXLttoL4uviY/soijXw/pqowHJnfpicJMCPqvXGha6welYOtthUSWnKcJjKbPCe9CCu0LWYwSDXz0canlNqBy0FptDKZR8Ue4k=,iv:264Ayj5SMYm5tKkm97ST+4rO9VTupH82LXtLSLzY0/w=,tag:Mfqjnz5uQtgMhkAzdfuxQA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRDlxVVFQTHB2MTh6aEU0
            WGRid2FFeTRGcjNpNXNqSE0yT1E0U29DTkNvClJWbk01QngzQWxmK2hsN01VNHpw
            dW9tY09oLytiMm16TldVRHNBWXdnVEUKLS0tIEtGOGN6amV1cWJyYXV5bXF2NzdI
            OTJVVkxkOG1IZ0pURVBTYWswYVRURnMK8sWhcrS0zP8DwViaSNixZqDyDIR4YVJ6
            efei4PadT3XQxrRmRlmkSzYCcqQD5j1dGhqVKaF1vqFiThaBam/7lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T20:52:04Z"
    mac: ENC[AES256_GCM,data:4ulFuvj5MRF8WAVp+ZL406vNsPykiQ50eXEAicrlWbFJC1TGf18QXnU/ud17Hjtm9CZ9pDYzecjpXRsD8bEBYFqG7U2Gb0bt6NkJcZdYJcgXU+98N9J232S+732n6UEg1n9CmJK6fbAOZwrWxBp0v0y1ookvB0W0x5K6he8cIpY=,iv:vRzvbePbJ0IXY1CuLhDSyMyHhPQTb3wsj2fTl9LakXU=,tag:25ZCpGGU5EWDhUKcYORF3Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
