apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:wsZ3fv0125PpqM2+nykmEWn91FY0o2w6ity9vnoeVpNo8NP2XLvH4D7g+TUqUtJgBNjtyVw/uVhfYDLvkRR9541t6vz1GvEqCMc=,iv:uNVos1uvtRpmxFEnBH1EPc19NcXC4DqnOF8f2+XvbHA=,tag:ZXA3IuQ6evsxkeSS1iM8tQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUW5uOElxdFRCTSt2a3VL
            bGErT0VTa0NITkxwUnM5amFiK0Q0ZS9NYkJFClBmTnlFMWYyRnl1V2JSYzlLV05a
            M0JSbGN2YXRuOWQ0VFpRUzlBcHkvbGcKLS0tIDVVSEVzeng3MHRhbHdkeTlHY1o3
            UHBlN2x1S0hoeGdyM281QVFHb3h6V0EKvrdcq7cdWtCJSNeKkTbgQ9z7DfHMEfT9
            sO/HidRFpqcZ+4tM9/LEdKUxH8aZ2VzRA+cA9WHsmnYeNKWaPWFbvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T16:24:32Z"
    mac: ENC[AES256_GCM,data:HZFg7aWtWd6a9wp7QNg0lYyN953jCvyIH17jz7CcpQ23iYTDyNFgaJbTputYYZDz0h944E5DBwc2iYBithWPRAV1w7VuOczm4W8oUhR9GymMzwDfZ5cPUQlMzr329RP/b65+olx67JxPb2+/WsMJN2cfSOifxfTvqVSD0vDSA1c=,iv:nRyb8OCwh8LECq/ClJFKStR9BgjetzW/CSHk/lwrRmU=,tag:+x8Czflev0hBFr/EXGxG1A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
