apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:jiPDcqY3HIJl/Dg9TjmkZfkRtXo+OHeti7b3lWRuTeJxNEjjNZQvf5HhxQd/Esb/szhlbcQnXK8t2c2CT0blvZDf7QssKRr1yLg=,iv:sHMOhKEhLUOamxLTskYsvzeIVEFB/Cofq/uphc/b5KU=,tag:HG6JgUtrxD/HdSBghnhVmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSHFhdWUrWm5NdHBJaTJR
            Ti8xYnNkd0pkNU02cytXTk90bXh5cHk3VmtNCjAzRlBYS011ZlVGek9xeTVxL0xE
            djhjRnZKUnFBbERleUtNRnRCeHJMZDQKLS0tIEI5SExsVHo2cUxqbnFkNkNiZlZO
            ZVhPVUY0Snp2OE82N1p6d2h4a1VTVTQKxZTbVbJcjyxgppDDxRTFR7bXaVNK2hX8
            YBa41l19YqgZutWOAJ4CVcB58VZB2wBXQpSTRAg7HUWF1Bi9+P0Ulw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T23:05:58Z"
    mac: ENC[AES256_GCM,data:jETSALenBTAhIPwATPKfFJca4mX/STNVyTIeozt5zJqaxKDI7ifj/UaZrWSk1PoGPk3nxOGaZvKTv8XbBfppbkQcosfW73O+h5KOAn5Tpaj8F7mhD7xTv8Bhpzhzyd6yWtHMZroC14IhNXOYkLu7hsV4pI6GFwF9Yr0YQCPD6Xc=,iv:/Z8hltzErCFd+kxNXjsd5qCOX5cRg8KE1yc9VBHerjg=,tag:G31xLdbmLqErpmRf6N5ZcA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
