apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:m2E+/yJYN3boQXeBpwjLt7hDZCW7HwLKfRH+9GbaSbZFy1miDiLz/ub3IvjE013tKmNABAOOMVbbHOymAU6xSvL558b3Bl291RQ=,iv:hZbURP1q8ivIE11umVhbvg7BwiLRRft5YEOOR/xAWYc=,tag:OcQ8stsZk2pgN6GsgL6UdQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSXU1eWhMVGdiTlNTbkRN
            N1pMOHlReVlsS3hVb21SSDJEUCtmM0NXQlgwClBuV254RXNsQzg1MkF0WklHZUJC
            Z0xBZWFyZzRPdC9aRHNOSGEwaDJKaHcKLS0tIHFaR2dmYWpVRkpzdjJPSEtQRG1j
            enBNWmlNeXovVFlOWEtHMHEyN3NrdWMKmfLqQpRZMTbRVODgMNwxpIaPZYZENyoF
            XGKnzP4ywPzDwgnm6twzKH0QEm8EbcG+V+1WzVqWTx1JOArfKHP8kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T14:58:53Z"
    mac: ENC[AES256_GCM,data:vtyEydZEA2wttsQVoPytr3m8rxJ+H68a+JVeR7jAQJPvcPoFgLFU8CghSzh0qdPJxRDqanRO5d1o+4Mlmbi0mPaFA9gst9UdDfBzEyCo4pyfvL6Gw7V2PYG6CNYiCydjsNSQY7oN/CxM3dd10j9AQ4ky8l2SAwNwIkfA6VSMq5A=,iv:3m6prIomv+Ja3G15AsaSp27ZksOqHoE0aFaZjfr1B7M=,tag:UujwbQ2labSGXRQobQHe6Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
